module.exports = {
  port: 3030,
  USE_HTTPS: false,
  TOKEN_SECRET: "%$JK%(^jfle^()_)^$bfd2e9283475kjdfhg^",
  QRCODE_GENERATION_URL: "QRCODE_GENERATION_URL",
  QRCODE_VERIFY_URL: "QRCODE_VERIFY_URL",
  SENDGRID_API_KEY: "SENDGRID_API_KEY",
  SENDER_EMAIL: "SENDER_EMAIL"
};
